
 export const menu = [
    {
      id:1,
      image:'/Images/pexels1.jpg',
      name:'',
      category:'garden'
    },
    {
      id:2,
      image:'/Images/pexels2.jpg',
      name:'',
      category:'indoor'
    },
    {
      id:3,
      image:'/Images/pexels3.jpg',
      name:'',
      category:'outdoor'
    },
    {
      id:4,
      image:'/Images/pexels4.jpg',
      name:'',
      category:'garden'
    },
    {
      id:5,
      image:'/Images/pexels5.jpg',
      name:'',
      category:'indoor'
    },
    {
      id:6,
      image:'/Images/pexels6.jpg',
      name:'',
      category:'outdoor'
    },
    {
      id:7,
      image:'/Images/pexels7.jpg',
      name:'',
      category:'garden'
    },
    {
      id:8,
      image:'/Images/pexels8.jpg',
      name:'',
      category:'indoor'
    },
    {
      id:9,
      image:'/Images/pexels9.jpg',
      name:'',
      category:'outdoor'
    },
    {
      id:10,
      image:'/Images/pexels10.jpg',
      name:'',
      category:'garden'
    },
    {
      id:11,
      image:'/Images/pexels11.jpg',
      name:'',
      category:'indoor'
    },
    {
      id:12,
      image:'/Images/pexels12.jpeg',
      name:'',
      category:'outdoor'
    },
   
    
  ]
  

  export const menu2 = [
    {
      id:13,
      image:'/Images/pexels13.jpeg',
      name:'',
      category:'garden'
    },
    {
      id:14,
      image:'/Images/pexels14.jpeg',
      name:'',
      category:'indoor'
    },
    {
      id:15,
      image:'/Images/pexels15.jpeg',
      name:'',
      category:'outdoor'
    },
    {
      id:16,
      image:'/Images/pexels16.jpeg',
      name:'',
      category:'garden'
    },
    {
      id:17,
      image:'/Images/pexels17.jpeg',
      name:'',
      category:'indoor'
    },
    {
      id:18,
      image:'/Images/pexels18.jpeg',
      name:'',
      category:'outdoor'
    },
    {
      id:19,
      image:'/Images/pexels19.jpeg',
      name:'',
      category:'garden'
    },
    {
      id:20,
      image:'/Images/pexels20.jpeg',
      name:'',
      category:'indoor'
    },
    {
      id:21,
      image:'/Images/pexels21.jpeg',
      name:'',
      category:'outdoor'
    },
    {
      id:22,
      image:'/Images/pexels22.jpeg',
      name:'',
      category:'garden'
    },
    {
      id:23,
      image:'/Images/pexels23.jpeg',
      name:'',
      category:'indoor'
    },
    {
      id:24,
      image:'/Images/pexels24.jpeg',
      name:'',
      category:'outdoor'
    },
  ]