
 export const menu = [
    {
      id:1,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1706709149/rawjbpuotuwkphokziyw.jpg',
      name:'',
      category:'indoor'
    },
   
    {
      id:2,
      image:'/Images/pexels3.jpg',
      name:'',
      category:'outdoor'
    },
    {
      id:3,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151683/garden/oxtabdbuzweabp7tqxb6.jpg',
      name:'',
      category:'garden'
    },
    {
      id:4,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1706816907/indoor/rc1fgvfprg2xqpddvcvq.jpg',
      name:'',
      category:'indoor'
    },
   
   
    {
      id:5,
      image:'/Images/pexels6.jpg',
      name:'',
      category:'outdoor'
    },
    {
      id:6,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151671/garden/euw3gg0jg9jywuq5ll5v.jpg',
      name:'',
      category:'garden'
    },
    {
      id:7,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1706816906/indoor/ww7pjllvzniuorzdoexy.jpg',
      name:'',
      category:'indoor'
    },
    {
      id:8,
      image:'/Images/pexels9.jpg',
      name:'',
      category:'outdoor'
    },
    {
      id:9,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151652/garden/shqwyydclmgty2kz0cfl.jpg',
      name:'',
      category:'garden'
    },
    {
      id:10,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1706816906/indoor/f4iz5ffuosywjwi3hkik.jpg',
      name:'',
      category:'indoor'
    },
    {
      id:11,
      image:'/Images/pexels12.jpeg',
      name:'',
      category:'outdoor'
    },
    {
      id:12,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151563/garden/ez51rexawue3f5dvmbc5.jpg',
      name:'',
      category:'garden'
    },
    {
      id:13,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816906/indoor/kjvnuokdni3ry1jzoavn.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:14,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816906/indoor/by4nklxlyqfnnlxxvxky.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:15,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816903/indoor/ft5s9q1lhuphvnofrk3v.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:16,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816902/indoor/wi20eulibf25m9hczgtj.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:17,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816901/indoor/evli1u3bdowr3hvucz6b.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:18,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816899/indoor/m3duyv8ebryrucpzmf6v.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:19,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816899/indoor/w4drajbxoa1xtey0tx1a.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:20,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816899/indoor/rcwdhrorrcga5tka3ypx.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:21,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816899/indoor/lkwoqrnmr1ncxfuvw5dc.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:22,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816899/indoor/txwdqjsxll1lsffyucta.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:23,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816898/indoor/laa1sbttu2gmfoghetae.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:24,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816897/indoor/iyrg9hixu6agjpeyzdft.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:25,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816897/indoor/szx5alehspyd4njvub0o.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:26,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816897/indoor/zf0eyfichavgugbwun1c.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:27,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816896/indoor/fd3atoi564caejhhodwg.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:28,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816896/indoor/kbph4voe0oyvgy8r3kaq.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:29,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816895/indoor/qq36u5f6umo8dl1wlazb.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:30,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816895/indoor/ukn6equngfyt1qfdpecl.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:31,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816895/indoor/jk45limafllkieqb9res.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:32,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816895/indoor/tqaszrddpvv76muq2xes.jpg",
      name:"",
      category:"indoor"
    },
    {
      id:33,
      image:"https://res.cloudinary.com/daar1gcw1/image/upload/v1706816895/indoor/fsnv3savg5nrrbzuaos1.jpg",
      name:"",
      category:"indoor"
    },
    {
    id:34,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151652/garden/shqwyydclmgty2kz0cfl.jpg',
      name:'',
      category:'garden'
    },
    {
      id:35,
      image:'/Images/pexels14.jpeg',
      name:'',
      category:'indoor'
    },
    {
      id:36,
      image:'/Images/pexels15.jpeg',
      name:'',
      category:'outdoor'
    },
    {
      id:37,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151620/garden/gx9lhh0gnlj0xnehefbh.jpg',
      name:'',
      category:'garden'
    },
    {
      id:38,
      image:'/Images/pexels17.jpeg',
      name:'',
      category:'indoor'
    },
    {
      id:39,
      image:'/Images/pexels18.jpeg',
      name:'',
      category:'outdoor'
    },
    {
      id:40,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151604/garden/miupkvcuoxsbtynal87k.jpg',
      name:'',
      category:'garden'
    },
    {
      id:41,
      image:'/Images/pexels20.jpeg',
      name:'',
      category:'indoor'
    },
    {
      id:42,
      image:'/Images/pexels21.jpeg',
      name:'',
      category:'outdoor'
    },
    {
      id:43,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151591/garden/u2shde6zejv1i91q3ago.jpg',
      name:'',
      category:'garden'
    },
    {
      id:44,
      image:'/Images/pexels23.jpeg',
      name:'',
      category:'garden'
    },
    {
      id:45,
      image:'/Images/pexels24.jpeg',
      name:'',
      category:'outdoor'
    },
    {
      id:46,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151577/garden/upl6iodu2acxdfhlj1gt.jpg',
      name:'',
      category:'garden'
    },
    {
      id:47,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1706816907/indoor/qghnkqydcpn7rwf3wwkh.jpg',
      name:'',
      category:'indoor'
    },
    
    {
      id:48,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151549/garden/nj9buazybthgogbqt6sf.jpg',
      name:'',
      category:'garden'
    },
    {
      id:49,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151538/garden/q4dgkr2oab8f4kngbnc0.jpg',
      name:'',
      category:'garden'
    },
    {
      id:50,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151522/garden/dwhr4okvdhfuicgpsdve.jpg',
      name:'',
      category:'garden'
    },
    {
      id:51,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151508/garden/nr935skx7fpxbthleqdz.jpg',
      name:'',
      category:'garden'
    },
    {
      id:52,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151492/garden/xp4lj9hgqeae7s4rnjnx.jpg',
      name:'',
      category:'garden'
    },
    {
      id:53,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151476/garden/jixndkkvfmfxhmydod3q.jpg',
      name:'',
      category:'garden'
    },
    
    {
      id:54,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151452/garden/yewb25716ri0weh3bonz.jpg',
      name:'',
      category:'garden'
    },
    {
      id:54,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151437/garden/v1ru0ieog1kvg4lhw4o7.jpg',
      name:'',
      category:'garden'
    },
    {
      id:55,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151411/garden/ihj0a0t0uajz5xlr7uum.jpg',
      name:'',
      category:'garden'
    },
    {
      id:56,
      image:'https://res.cloudinary.com/daar1gcw1/image/upload/v1707151384/garden/mcdxrcjtsfhxfbvwdwad.jpg',
      name:'',
      category:'garden'
    },
    
  ]
  

  